version: '3'

services:
  postgres-emailn:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin-emailn:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "80:80"
    depends_on:
      - postgres-emailn
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge